### ISSUE TITLE
What is visible pre-login?

### ISSUE THREAD

**Issue by bluefibonacci** [VTResilienceLab/oscurrency#435]
I'd like to see an option for admins to have some functions available before login.  I believe this would lead more people to join and enable more transactions. 

For instance, if requests were available before login, someone could see a request for something they do. After they have read the data, they can login or choose to join the exchange at that point. 

I think this is a more modern expectation that having someone learn about an exchange and submit a form. The individual transactions are the hook that bring people in and we have no way to pre-show people how they could be involved.

**Comment by amykirschner** [comment]
Offers have been made public, requests yet to be done.
